"""add intent patterns

Revision ID: 05b345290054
Revises: b31bd9157ace
Create Date: 2026-08-08 23:32:17.024435

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05b345290054"
down_revision: str | Sequence[str] | None = "b31bd9157ace"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intent_patterns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("intent", sa.String(length=50), nullable=False),
        sa.Column("pattern", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "intent", "pattern", name="uq_intent_patterns_business_intent_pattern"
        ),
    )
    op.create_index(
        op.f("ix_intent_patterns_business_id"), "intent_patterns", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_intent_patterns_tenant_id"), "intent_patterns", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_intent_patterns_tenant_id"), table_name="intent_patterns")
    op.drop_index(op.f("ix_intent_patterns_business_id"), table_name="intent_patterns")
    op.drop_table("intent_patterns")
    # ### end Alembic commands ###
