"""add agent scoping and knowledge cache settings

Revision ID: d2935664026c
Revises: 9d05681b8efc
Create Date: 2026-08-09 15:01:28.876930

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2935664026c"
down_revision: str | Sequence[str] | None = "9d05681b8efc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answered_questions",
        sa.Column("agent_id", sa.String(length=255), server_default="default", nullable=False),
    )
    op.create_index(
        op.f("ix_answered_questions_agent_id"), "answered_questions", ["agent_id"], unique=False
    )
    op.add_column(
        "businesses",
        sa.Column("knowledge_scope", sa.String(length=20), server_default="shared", nullable=False),
    )
    op.add_column("businesses", sa.Column("knowledge_ttl_days", sa.Integer(), nullable=True))
    op.add_column(
        "decision_log",
        sa.Column("agent_id", sa.String(length=255), server_default="default", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("decision_log", "agent_id")
    op.drop_column("businesses", "knowledge_ttl_days")
    op.drop_column("businesses", "knowledge_scope")
    op.drop_index(op.f("ix_answered_questions_agent_id"), table_name="answered_questions")
    op.drop_column("answered_questions", "agent_id")
    # ### end Alembic commands ###
