from pydantic import BaseModel, Field


class AssistantMessageRequest(BaseModel):
    """Request containing the response generated by the customer's LLM."""

    text: str = Field(min_length=1)


class AssistantMessageResponse(BaseModel):
    """Confirmation that the assistant response was stored."""

    conversation_id: str
    stored: bool
