from fastapi import APIRouter

from backend.app.api.schemas.conversation import (
    AssistantMessageRequest,
    AssistantMessageResponse,
)
from backend.app.api.schemas.inference import (
    InferenceRequestBody,
    InferenceResponseBody,
)
from backend.app.application.conversation import ConversationService
from backend.app.application.inference import InferenceService
from backend.app.domain.inference import InferenceRequest
from backend.app.infrastructure.conversation.in_memory import (
    InMemoryConversationStore,
)
from backend.app.infrastructure.matching.rule_based import RuleBasedIntentMatcher

router = APIRouter(
    prefix="/v1",
    tags=["inference"],
)

conversation_store = InMemoryConversationStore()

inference_service = InferenceService(
    intent_matcher=RuleBasedIntentMatcher(),
    conversation_store=conversation_store,
)

conversation_service = ConversationService(
    conversation_store=conversation_store,
)


@router.post("/inference", response_model=InferenceResponseBody)
async def inference(
    request: InferenceRequestBody,
) -> InferenceResponseBody:
    """Process an STT request through the RelayAI inference layer."""

    result = await inference_service.process(
        InferenceRequest(
            business_id=request.business_id,
            conversation_id=request.conversation_id,
            text=request.text,
        )
    )

    return InferenceResponseBody(
        action=result.action,
        text=result.text,
        source=result.source,
        intent=result.intent,
    )


@router.post(
    "/conversations/{conversation_id}/messages",
    response_model=AssistantMessageResponse,
)
async def record_assistant_message(
    conversation_id: str,
    request: AssistantMessageRequest,
) -> AssistantMessageResponse:
    """Store an assistant response generated by the customer's LLM."""

    await conversation_service.record_assistant_response(
        conversation_id=conversation_id,
        text=request.text,
    )

    return AssistantMessageResponse(
        conversation_id=conversation_id,
        stored=True,
    )
